### ISSUE TITLE
Empty vcf

### ISSUE THREAD

**Issue by SarahBailey1998** [ndierckx/Sim-it#10]
Hi, Thank you for creating Sim-it. I enjoyed your benchmarking paper and I have been trying to run Sim-it. I am trying to run it on a single chromosome (26 Mb). I have tried running it with the default values for length, copies, heterozygosity, range and accuracy and some random values for the count. After completing the run, my VCF file is empty. What am I doing wrong?

This is my config file:

```text
Project:
-----------------------------
Project name             = Ch8_test3
Reference sequence       = /SV_calling/data/ch8/Ch8.only.fsa
Replace ambiguous nts(N) =


Structural variation:
-----------------------------
VCF input                =

Foreign sequences        =

Deletions                = 5
Length (bp)              = 30-150000

Insertions               = 5
Length (bp)              = 30-100000

Tandem duplications      = 2
Length (bp)              = 50-10000
Copies                   = 1-20

Inversions               = 2
Length (bp)              = 150-650000

Complex substitutions    = 2
Length (bp)              = 30-100000

Inverted duplications    = 2
Length (bp)              = 150-350000

Heterozygosity           = 60%


Read simulation:
-----------------------------
Sequencing depth         = 30

Median length            = 11000
Length range             = 500-150000

Accuracy                 = 94%
Error profile            = ./Sim-it/error_profile_ONT.txt
```

**Comment by ndierckx** [comment]
Hi,
It should not be empty, not sure what happened.
You didn't get any error? 
And can you try with the latest version and config file from github?

**Comment by SarahBailey1998** [comment]
Hi,
Thanks for getting back to me so quickly. I downloaded the latest version and ran it with chromosome 1 from the GRCh38 reference genome and the VCF file is no longer empty, however I get the error:

```text
cat: /SV_calling/Simulating_data/Sim-it_human_Ch1/Long_reads_Test_human_Ch1_HAP1.fasta: No such file or directory
cat: /SV_calling/Simulating_data/Sim-it_human_Ch1/Long_reads_Test_human_Ch1_HAP2.fasta: No such file or directory
```
It seems that those files mentioned in the error are not created. Long_reads_Test_human_Ch1_HAP12.fasta is created but is empty. If I use v1.3.2 with the same FASTA file, I don't get this error.

When I use my own genome with v1.3.3, my VCF file is still empty. Could the format of my FASTA file be causing this error? How many bases should be printed on each line of the FASTA file? Is soft-masking allowed?

Thank you!

**Comment by ndierckx** [comment]
Never encountered those issues, maybe there is a problem with you Perl version
Could you send me the log file?
And which OS are you using?

**Comment by ndierckx** [comment]
Hi,

Sorry, I just saw there was a little bug in that version, it should be fixed in 1.3.4

**Comment by SarahBailey1998** [comment]
Hi,
I managed to fix the empty VCF error. I assumed that the FASTA file I was using was the issue since Sim-it worked fine with human Ch1. The differences between my FASTA and human Ch1 was that my FASTA had soft-masking and was a sequential FASTA. Below are the steps I took to prepare my genome to run with Sim-it.

First, I removed the soft-masking:
```text
# from https://www.networkworld.com/article/3529409/converting-between-uppercase-and-lowercase-on-the-linux-command-line.html

cat Ch8.only.fa | tr [:lower:] [:upper:] >> Ch8.only.no_soft_masking.fa
```
Then, I converted my sequential fasta to interleaved fasta:
```text
# from: https://www.biostars.org/p/205745/#295738

ml seqkit # v0.7.0

seqkit seq -w 60 Ch8.only.no_soft_masking.fa > Ch8.only.no_soft_masking.interleaved.fa
```

I used Sim-it v1.3.4.

**Comment by ndierckx** [comment]
Hi,

Thanks for the info. Are you sure soft-masking is an issue? Because it shouldn't
With sequential fasta, do you mean the whole chromosome was written as one line?

And is that file 'Ch8.only.fa' somewhere online available, then I will test it to fix the issue?

Greets,

Nicolas

**Comment by SarahBailey1998** [comment]
Hi,

I just checked and the soft-masking is not an issue as you said.

And yes, that's exactly what I mean by sequential fasta. Ch8 is not available online but you could convert another FASTA from interleaved to sequential and test that file.

Below is an example of how you could do that using human Ch1:
```text
ml samtools/1.12 seqtk/1.2

# download and prepare reference (from https://davidebolo1993.github.io/visordoc/usecases/usecases.html#visor-hack)
while true; do
    wget -T 15 -c ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa && break
done

samtools faidx GRCh38_full_analysis_set_plus_decoy_hla.fa chr1:0-2489564 > smallref.fa

# from https://www.biostars.org/p/9262/
seqtk seq -l0 smallref.fa > smallref_singleLines.fa
``` 
Thanks

**Comment by steven-solar** [comment]
I'm having this same problem. Tried to remove masking and wrap the FASTA, but still does not generate the output vcf file of the SVs. I'm using chr1 of chm13v2.0.fasta and the example input vcf provided (subsetted to just chr1, replacing "1" with "chr1" to match assembly chromosome names) just as a test.

**Comment by ndierckx** [comment]
Hi,

Sorry I haven't worked on this github page for a while, will submit a new version tomorrow. But the header of chm13v2.0.fasta is ">chr1 CP068277.2 Homo sapiens isolate CHM13 chromosome 1", have you tried to change it to chr1 in the fasta file ?

**Comment by m-bogaerts** [comment]
Hello,

I am having the same problem. I tried to use only one chromosome and named it as "chr4" but I still get:
cat: dtolc4/Long_reads_Test_HAP1.fasta: No such file or directory
cat: dtolc4/Long_reads_Test_HAP2.fasta: No such file or directory

Have anybody solved it?

Thank you in advance.

**Comment by ndierckx** [comment]
Can you try again with version 1.3.5 that I just uploaded?

**Comment by m-bogaerts** [comment]
Hello,

Thank you very much for your answer.

With version 1.3.5 I still have the same problem:
Sim-it
Version 1.3.5
Author: Nicolas Dierckxsens, (c) 2020-2023
.
.
.
cat: dtolc4/Long_reads_Test_HAP1.fasta: No such file or directory
cat: dtolc4/Long_reads_Test_HAP2.fasta: No such file or directory

Sorry for the inconveniences and thank you in advance.

**Comment by ndierckx** [comment]
Can you send me your config file and log file?
